GET http://localhost:3000/contacts


### GET /contacts/:id
GET http://localhost:3000/contacts/6484888b0e0480ec425e1cf0
// Send Request

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Ivan",
    "lastName": "Aranas",
    "email": "izech@email.com",
    "favoriteColor": "Purple",
    "birthday": "08/03/2010"
}
// Send Request

### PUT contact
PUT http://localhost:3000/contacts/648a24b596676a9e5c7e87f3 HTTP/1.1
content-type: application/json

{
    "firstName": "Izech",
    "lastName": "Aranas",
    "email": "izech@email.com",
    "favoriteColor": "Green",
    "birthday": "08/03/2010"
}

### DELETE contact
DELETE http://localhost:3000/contacts/648a24b596676a9e5c7e87f3 HTTP/1.1

### Request for API Docs
GET http://localhost:3000/api-docs